
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SpecFirst source generator.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecFirst.Core.Specs.Tests
{
    using System;
    using System.Collections.Generic;
    using Xunit;
    
    public partial class is_table_a_decision_table
    {
        private static readonly string table_with_one_row = "<table>\n  <tbody>\n    <tr>\n      <td> Column </td>\n    </tr>\n  </tbody>\n</table>\n";
        private static readonly string decision_table_with_theader = "<table>\n  <thead>\n    <tr>\n      <td colspan=\"2\"> Table Name </td>\n    </tr>\n    <tr>\n      <td> Table Header 1 </td>\n      <td> Table Header 2? </td>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td> Table Data 1 </td>\n      <td> Table Data 2 </td>\n    </tr>\n  </tbody>\n</table>\n";
        private static readonly string setup_decision_table = "<table>\n  <tbody>\n    <tr>\n      <td colspan=\"2\"> setup:Column 1 </td>\n    </tr>\n    <tr>\n      <td> Table Header 1 </td>\n      <td> Table Header 2? </td>\n    </tr>\n    <tr>\n      <td> Table Data 1 </td>\n      <td> Table Data 2 </td>\n    </tr>\n  </tbody>\n</table>\n";
        private static readonly string comment_decision_table = "<table>\n  <tbody>\n    <tr>\n      <td colspan=\"2\"> comment:Table Name </td>\n    </tr>\n    <tr>\n      <td> Table Header 1 </td>\n      <td> Table Header 2? </td>\n    </tr>\n    <tr>\n      <td> Table Data 1 </td>\n      <td> Table Data 2 </td>\n    </tr>\n  </tbody>\n</table>\n";
        private static readonly string table_with_only_comments = "<table>\n  <tbody>\n    <tr>\n      <td colspan=\"2\"> Table Name </td>\n    </tr>\n    <tr>\n      <td> #Table Header 1 </td>\n      <td> #Table Header 2 </td>\n    </tr>\n    <tr>\n      <td> Table Data 1 </td>\n      <td> Table Data 2 </td>\n    </tr>\n  </tbody>\n</table>\n";
        private static readonly string table_with_missing_data_in_second_row = "<table>\n  <tbody>\n    <tr>\n      <td colspan=\"2\"> Column 1 </td>\n    </tr>\n    <tr>\n      <td> Column 1 </td>\n      <td>  </td>\n    </tr>\n    <tr>\n      <td> Column 1 </td>\n      <td> Column 2 </td>\n    </tr>\n  </tbody>\n</table>\n";
        private static readonly string table_with_three_row_and_multi_columns = "<table>\n  <tbody>\n    <tr>\n      <td> Column 1 </td>\n      <td> Column 2 </td>\n    </tr>\n    <tr>\n      <td> Column 1 </td>\n      <td> Column 2 </td>\n    </tr>\n    <tr>\n      <td> Column 1 </td>\n      <td> Column 2 </td>\n    </tr>\n  </tbody>\n</table>\n";
        private static readonly string table_with_missing_data_in_first_row = "<table>\n  <tbody>\n    <tr>\n      <td colspan=\"2\">  </td>\n    </tr>\n    <tr>\n      <td> Column 1 </td>\n      <td> Column 2 </td>\n    </tr>\n    <tr>\n      <td> Column 1 </td>\n      <td> Column 2 </td>\n    </tr>\n  </tbody>\n</table>\n";
        private static readonly string decision_table = "<table>\n  <tbody>\n    <tr>\n      <td colspan=\"2\"> Table Name </td>\n    </tr>\n    <tr>\n      <td> Table Header 1 </td>\n      <td> Table Header 2? </td>\n    </tr>\n    <tr>\n      <td> Table Data 1 </td>\n      <td> Table Data 2 </td>\n    </tr>\n  </tbody>\n</table>\n";
        
        [Theory]
        [MemberData(nameof(get_test_data))]
        public void is_table_a_decision_table_tests(string decision_table, bool is_valid, string validation_error)
        {
            (bool is_valid_output, string validation_error_output) = is_table_a_decision_table_implementation(decision_table);
            Assert.Equal(is_valid_output, is_valid);
            Assert.Equal(validation_error_output, validation_error);
        }

        public static IEnumerable<object[]> get_test_data()
        {
            var data = new List<object[]>
            {
                new object[] { table_with_one_row, false, "Decision table must have at least three rows" }, // Table with only 1 row
                new object[] { table_with_three_row_and_multi_columns, false, "The first row of the decision table must have a single column" }, // Table with 3 rows but the first row has multiple columns
                new object[] { table_with_missing_data_in_first_row, false, "The first row of the decision table must contain some text" }, // Table with no text in the first row
                new object[] { table_with_missing_data_in_second_row, false, "The second row of the decision table must contain some text in each column" }, // Table with missing text in the second row
                new object[] { table_with_only_comments, false, "The second row of the decision table must contains at least one column that is not a comment column" }, // Table with only comments
                new object[] { decision_table, true, "" }, // A valid decision table
                new object[] { decision_table_with_theader, true, "" }, // A valid decision table with thead section
                new object[] { comment_decision_table, true, "" }, // A valid comment decision table
                new object[] { setup_decision_table, true, "" }, // A valid setup decision table
            };

            return data;
        }

        private partial (bool, string) is_table_a_decision_table_implementation(string decision_table);
    }

}