namespace SpecFirst.TestGenerator.xUnit.Template
{
    public class XUnitTemplate
    {
        public const string TEST_FILE_TEMPLATE =
@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SpecFirst source generator.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace {{namespace_name}}
{
    using System;
    using System.Collections.Generic;
    using Xunit;
    
    {{#each list_of_fixtures}}
    {{#if is_setup_table}}
    {{> SETUP_CLASS_TEMPLATE}}
    {{else}}
    {{> TEST_CLASS_TEMPLATE}}
    {{/if}}
    {{/each}}

    {{#if contains_setup}}
    {{> COLLECTION_DEFINITION_TEMPLATE}}
    {{/if}}
}
";

        public const string IMPLEMENTATION_FILE_TEMPLATE =
@"namespace {{namespace_name}}
{
    using System;

    {{#each list_of_fixtures}}
    {{> IMPLEMENTATION_CLASS_TEMPLATE}}
    {{/each}}
}";

        public const string TEST_CLASS_TEMPLATE =
@"  {{#if collection_fixtures}}
    [Collection(""test_collection"")]
    {{/if}}
    {{#if class_fixtures}}
    {{> TEST_CLASS_NAME_TEMPLATE}} : {{class_fixtures}}
    {{else}}
    {{> TEST_CLASS_NAME_TEMPLATE}}
    {{/if}}
    {
        {{> CLASS_VARIABLE_TEMPLATE}}
        
        {{#if collection_or_class_fixtures}}
        public {{class_name}}({{collection_or_class_fixtures}})
        {
            {{#each setup_variables}}
            {{{this}}};
            {{/each}}
        }
        {{/if}}

        [Theory]
        [MemberData(nameof(get_test_data))]
        {{> TEST_METHOD_TEMPLATE}}
        {
            {{> DECORATION_VARIABLE_TEMPLATE}}
            {{> IMPL_METHOD_CALL_EXPRESSION_TEMPLATE}}
            {{> ASSERT_STATEMENT_TEMPLATE}}
        }

        {{> TEST_DATA_TEMPLATE}}

        {{> IMPL_METHOD_DECLARATION_TEMPLATE}}

        {{> DECORATION_METHOD_TEMPLATE}}
    }
}
";

        public const string SETUP_CLASS_TEMPLATE =
@"  {{> TEST_CLASS_NAME_TEMPLATE}} : IDisposable
    {
        {{> CLASS_VARIABLE_TEMPLATE}}
        public {{class_name}}()
        {
            foreach (var data in get_test_data())
            {
                {{> DECORATION_VARIABLE_TEMPLATE}}
                {{> IMPL_METHOD_CALL_EXPRESSION_TEMPLATE}}
                {{> ASSERT_STATEMENT_TEMPLATE}}
            }
        }

        {{> TEST_DATA_TEMPLATE}}

        {{> IMPL_METHOD_DECLARATION_TEMPLATE}}

        {{> DECORATION_METHOD_TEMPLATE}}
    }
}
";

        public const string IMPLEMENTATION_CLASS_TEMPLATE =
@"  {{> TEST_CLASS_NAME_TEMPLATE}}
    {
        {{> IMPL_METHOD_TEMPLATE}}
        {
            throw new NotImplementedException();
        }
    }
}
";

        public const string TEST_DATA_TEMPLATE =
@"        public static IEnumerable<object[]> get_test_data()
        {
            var data = new List<object[]>
            {
                {{#each test_data_and_comments}}
                new object[] { {{{this.TestData}}} }, // {{{this.Comment}}}
                {{else}}
                new object[] { {{{this.TestData}}} },
                {{/if}}
                {{/each}}
            };

            return data;
        }
";

        public const string IMPL_METHOD_DECLARATION_TEMPLATE =
@"        private partial {{impl_return_types}} {{class_name}}_implementation({{impl_input_parameters}});
";

        public const string IMPL_METHOD_TEMPLATE =
@"        private partial {{impl_return_types}} {{class_name}}_implementation({{impl_input_parameters}})
";

        public const string DECORATION_METHOD_TEMPLATE =
@"        {{#if decoration_methods}}
        {{#each decoration_methods}}
        private partial {{this.ReturnType}} {{this.ParameterName}}_implementation({{this.InputParameters}});
        {{/each}}

        {{/if}}";

        public const string CLASS_VARIABLE_TEMPLATE =
@"        {{#if class_variables}}
        {{#each class_variables}}
        {{#if this.VariableValue}}
        private static readonly {{this.VariableType}} {{this.VariableName}} = {{{this.VariableValue}}};
        {{else}}
        public static readonly {{this.VariableType}} {{this.VariableName}};
        {{/if}}
        {{/each}}

        {{/if}}";

        public const string TEST_METHOD_TEMPLATE =
@"        public void {{class_name}}_tests({{test_parameters}})
";

        public const string IMPL_METHOD_CALL_EXPRESSION_TEMPLATE =
@"            {{#if impl_return_values}}
            {{impl_return_values}} = {{class_name}}_implementation({{impl_arguments}});
            {{else}}
            {{class_name}}_implementation({{impl_arguments}});
            {{/if}}";

        public const string ASSERT_STATEMENT_TEMPLATE =
@"            {{#each assert_statements}}
            {{{this}}};
            {{/each}}";

        public const string ASSIGN_STATEMENT_TEMPLATE =
@"            {{#each assign_statements}}
            {{{this}}};
            {{/each}}";

        public const string DECORATION_VARIABLE_TEMPLATE =
@"            {{#if decoration_variables}}
            {{#each decoration_variables}}
            {{{this}}};
            {{/each}}

            {{/if}}";

        public const string TEST_CLASS_NAME_TEMPLATE =
@"    public partial class {{class_name}}
";
        public const string COLLECTION_DEFINITION_TEMPLATE =
@"    {{#if collection_fixtures}}
      [CollectionDefinition(""test_collection"")]
      public class test_collection : {{collection_fixtures}}
      {
         // This class has no code, and is never created. Its purpose is simply
         // to be the place to apply [CollectionDefinition] and all the
         // ICollectionFixture<> interfaces.
      }
      {{/if}}";
    }
}
